services:
  keycloak:
    container_name: keycloak-social-media
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123456
    ports:
      - 9090:8080
    networks:
      - social-media
    command:
      - "start-dev"

networks:
  social-media:
    driver: bridge