spring:
  application:
    name: post-service
  config:
    import: configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/social-media"
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: info:com.tqkien03.postservice.messaging.PostEventInfo
    consumer:
      bootstrap-servers: localhost:9092
      group-id: reactGroup,commentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: reactEventInfo:com.tqkien03.postservice.messaging.ReactEventInfo,commentEventInfo:com.tqkien03.postservice.messaging.CommentEventInfo

application:
  config:
    react-url: http://localhost:8014/api/v1/reacts