spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/social-media"
  mail:
    host: smtp.gmail.com
    port: 587
    username: quangkienta3@gmail.com
#    password: ${EMAIL_PASSWORD}
    password: jkamngfgaldjqmwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account