eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false

application:
  config:
    user-url: http://localhost:8011/api/v1/users
    post-url: http://localhost:8012/api/v1/posts
    media-url: http://localhost:8013/api/v1/medias