spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/v1/auth/**
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/users/**

eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

#management:
#  tracing:
#    sampling:
#      probability: 1.0

